### ISSUE TITLE
Configure 3rd party services and tools

### ISSUE THREAD

**Issue by andrewmarklloyd** [crablar/podsheets#21]
- [x] Access to AWS bucket for profile pics
- [x] Configure or remove Zendesk?

**Comment by andrewmarklloyd** [comment]
@crablar can you add me access to the S3 bucket? Also are we going to reenable Zendesk or remove it?

**Comment by crablar** [comment]
Can we move the S3 functionality over to Google since we are using bucket storage there already?

I think we should leave out Zendesk for now though I will let @fukuru decide if he wants to leave it in.

**Comment by andrewmarklloyd** [comment]
I thought about this too, we should just move S3 bucket to using Google. @fukuru can you do this?

**Comment by fukuru** [comment]
@andrewmarklloyd @crablar Yeah I can move S3 to Google. Can you guys grant me access to AWS console?

**Comment by andrewmarklloyd** [comment]
@fukuru actually now that I’m looking more into this, I was mixing software daily and Podsheets configurations. AWS buckets are only used by the social site which were holding off on. We can ignore this @crablar

**Comment by fukuru** [comment]
@andrewmarklloyd Can we close this?

**Comment by andrewmarklloyd** [comment]
As long as we remove or configure zendesk

**Comment by fukuru** [comment]
Ok I will remove Zendesk in #34. If need be we can use Intercom's chat widget for support.

**Comment by andrewmarklloyd** [comment]
Sounds good
