### ISSUE TITLE
Generator tag in RSS feed should be "Podsheets (https://podsheets.com)"

### ISSUE THREAD

**Issue by jeremyjung** [crablar/podsheets#56]
The <generator> tag in the RSS feed reads "Podcast for Node".  I believe this tag is intended to describe who generated the feed, which in this case is "Podsheets (https://podsheets.com)"

**Comment by andrewmarklloyd** [comment]
@jeremyjung I updated the generator tag to use `Podsheets - https://www.podsheets.com`
